import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import remark from 'remark'
import html from 'remark-html'

// Get the content directory:
// - Since Next.js compiles the code into a separate directory you can't use __dirname as the path it will return will be different from the pages directory.
// - Instead you can use process.cwd() which gives you the directory where Next.js is being executed. 
const projectsDirectory = path.join(process.cwd(), 'content/projects')

// ==============================
// This function returns a list of projects in the format "lang/project_id.md":
function getAllProjectFileNames(directoryPath, filesList = []) {
  const files = fs.readdirSync(directoryPath)

  files.forEach((file) => {
    if (fs.statSync(`${directoryPath}/${file}`).isDirectory()) {
      filesList = getAllProjectFileNames(`${directoryPath}/${file}`, filesList)
    } else {
      filesList.push(path.join(path.basename(directoryPath), "/", file))
    }
  })

  // Filter to include only * .md files (and avoid files like .DS_Stores):
  const filteredList = filesList.filter((file) => file.includes(".md"))
  return filteredList
}

// ==============================
// This function creates a list with all the combinations of projects IDs and locales, which will be used for the paths of the Dynamic Routes:
// - It will be used by the getStaticPaths of the project (/projects/[id].js).
// - For dynamic getStaticProps pages, any locale variants of the page that is desired to be prerendered needs to be returned from getStaticPaths. 
// - Along with the params object that can be returned for the paths, you can also return a locale field specifying which locale you want to render.
// - The format should be like this:
// - [
// -   { params: { id: 'projectId' }, locale: 'lang' },
// -   { params: { id: 'projectId' }, locale: 'lang' },
// - ]
export function getAllProjectIds() {
  const fileNames = getAllProjectFileNames(projectsDirectory)
 
  // Create the paths iterating through the list generated by getAllProjectFileNames:
  return fileNames.map((fileName) => ({
    params: { id: fileName.split("/")[1].replace(/\.md$/, ""), },
    locale: fileName.split("/")[0],
  }))  

}

// ==============================
// This function creates the data for the projects index:
// - It will be used by the getStaticProps of the projects index (/index.js):
export function getProjectsData(currentLocale) {
  const fileNames = getAllProjectFileNames(projectsDirectory)

  // Create the data for each project iterating through the list generated by getAllProjectFileNames:
  const projectsData = fileNames.map(fileName => {
    // Remove ".md" from file name to get ID:
    const id = fileName.split("/")[1].replace(/\.md$/, "")
    // Get the locale:
    const locale = fileName.split("/")[0]
    // Read markdown file as string:
    const fullPath = path.join(projectsDirectory, fileName)
    const fileContents = fs.readFileSync(fullPath, 'utf8')
    // Use gray-matter to parse the project metadata section:
    const matterResult = matter(fileContents)
    // Combine the metadata with the ID and the locale:
    return {
      id,
      locale,
      ...matterResult.data
    }
  })

  // Filter by the current language:
  const filteredProjectsData = projectsData.filter((project) => project.locale === currentLocale)
  // Sort the projects by position:
  return filteredProjectsData.sort((a, b) => {
    if (a.position < b.position) {
      return -1
    } else {
      return 1
    }
  })
}

// ==============================
// This function creates the data of a specific project:
// - It will be used by the getStaticProps of the project (/projects/[id].js):
export async function getProjectData(locale_ProjectId) {

  // Get the content from the project file:
  const fullPath = path.join(projectsDirectory, `${locale_ProjectId}.md`)
  const fileContents = fs.readFileSync(fullPath, 'utf8')

  // Use gray-matter to parse the project metadata section:
  const matterResult = matter(fileContents)

  // Use remark to convert markdown into HTML string:
  const processedContent = await remark()
    .use(html)
    .process(matterResult.content)
  const contentHtml = processedContent.toString()
  
  // Combine the metadata with the contentHtml and the locale_ProjectId:
  return {
    locale_ProjectId,
	  contentHtml,
    ...matterResult.data
  }
}